[build]
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "18.19.0"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/topics/programming"
  to = "/topics/programming/"
  status = 301
  force = true

[[redirects]]
  from = "/topics/design"
  to = "/topics/design/"
  status = 301
  force = true

[[redirects]]
  from = "/topics/writing"
  to = "/topics/writing/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 