[build]
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "18.19.0"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/topics/programming"
  to = "/topics/programming/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/design"
  to = "/topics/design/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/writing"
  to = "/topics/writing/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics"
  to = "/topics/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/programming/"
  to = "/topics/programming/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/design/"
  to = "/topics/design/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/writing/"
  to = "/topics/writing/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/topics/"
  to = "/topics/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 