backend:
  name: github
  repo: beastnyc/Digital-garden
  branch: main
  base_url: https://api.netlify.com

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/docs/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "topics"
    label: "Topics"
    folder: "src/content/docs/topics"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 