backend:
  name: github
  repo: beastnyc/digital-garden
  branch: main
  base_url: https://biancaherbert.netlify.app

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/docs/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Status", name: "status", widget: "select", options: ["evergreen", "budding", "seedling"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "topics"
    label: "Topics"
    folder: "src/content/docs/topics"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Entry Count", name: "entryCount", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"} 