backend:
  name: github
  repo: beastnyc/Digital-garden
  branch: main

site_url: https://cozy-fudge-f09e4f.netlify.app
display_url: https://cozy-fudge-f09e4f.netlify.app

publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

local_backend: true

collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/docs/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "yaml-frontmatter"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss [UTC]"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "topics"
    label: "Topics"
    folder: "src/content/docs/topics"
    create: true
    slug: "{{slug}}"
    format: "yaml-frontmatter"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 